CLAN:
  SIZE: 40
  ALLYS: 1
  HELP:
    - "{bars}"
    - "&5&lComandos de Clans &7(Usuario)"
    - "&7» &d/clan create (name)"
    - "&7» &d/clan show"
    - "&7» &d/clan join (clan)"
    - "&7» &d/clan leave"
    - "&7» &d/clan msg (message)"
    - "&7» &d/clan chest"
    - "&7» &d/clan topkills"
    - "{bars}"
    - "&5&lComandos de Clans &7(Leader a Mod del Clan)"
    - "&7» &d/clan delete"
    - "&7» &d/clan invite (player)"
    - "&7» &d/clan uninvite (player)"
    - "&7» &d/clan kick (player)"
    - "&7» &d/clan setpvp (true/false)"
    - "&7» &d/clan addmoderator (player)"
    - "&7» &d/clan removemoderator (player)"
    - "&7» &d/clan removecoleader (player)"
    - "&7» &d/clan rename (newName)"
    - "&7» &d/clan setleader (player)"
    - "&7» &d/clan setcoleader (player)"
    - "{ops}"
    - "{bars}"
  OPS_HELP:
    - "{bars}"
    - "&5&lComandos de Clans &7(Staff)"
    - "&7» &d/clan forcejoin (clan)"
    - "&7» &d/clan forcedelete (clan)"
    - "&7» &d/clan forcesetleader (clan)"
  NIVELES: " &7» {color}{level} &7\u007C {identifier}"